### ISSUE TITLE
Florence2ModelLoader node not found

### ISSUE THREAD

**Issue by fafayqa** [kijai/ComfyUI-Florence2#105]
I was told this repo contains also the Florence2ModelLoader node which I need for some workflow form 3rd party I am trying to use. Can you tell me where it is and how to obtain it, please?

**Comment by kijai** [comment]
I'm not sure I understand the question, it should be right there when you search for it? 

![image](https://github.com/user-attachments/assets/577160ba-35f2-4304-b56d-da16a5b9316a)

You have the other nodes working?

**Comment by fafayqa** [comment]
no, it is not, I see:
Florence2Run
DownloadAndLoadFlorence2Model
DownloadAndLoadFlorence2Lora

**Comment by kijai** [comment]
> no, it is not, I see: Florence2Run DownloadAndLoadFlorence2Model DownloadAndLoadFlorence2Lora
> 
> I am on the latest ComfyUI Portable v0.3.9 from their official Github URL at https://github.com/comfyanonymous/ComfyUI/releases

Then you must have very old version of these nodes.

**Comment by fafayqa** [comment]
yes, I just noticed error in the log file,. see:

[ERROR] An error occurred while retrieving information for the 'Florence2ModelLoader' node.
Traceback (most recent call last):
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\server.py", line 579, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\server.py", line 546, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 150, in INPUT_TYPES
    "model": ([item.name for item in Path(folder_paths.models_dir, "LLM").iterdir() if item.is_dir()], {"tooltip": "models are expected to be in Comfyui/models/LLM folder"}),
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pathlib.py", line 1056, in iterdir
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'Z:\\_PSTART_\\_APPS_\\_AI_\\ComfyUI_windows_portable\\ComfyUI\\models\\LLM'

Now the question for me is: WHAT IS LLM? Sorry, but I am new to AI and this stuff, so would you be so kind and tell me?  Is it a model from Civitai webpage?

**Comment by fafayqa** [comment]
**UPDATE:**
Yes, simple folder creation did the trick, it now shows the node.
