### ISSUE TITLE
SyntaxWarning: "is not" with a literal. Did you mean "!="?   if text_input is not ""

### ISSUE THREAD

**Issue by RGX650** [kijai/ComfyUI-Florence2#16]
Total VRAM 16384 MB, total RAM 64780 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.27.dev792
Set vram state to: LOW_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 Ti Laptop GPU : cudaMallocAsync
Using xformers cross attention
Adding extra search path checkpoints C:/AI/SDNEXT/automatic/models/Stable-diffusion
Adding extra search path configs C:/AI/SDNEXT/automatic/models/Stable-diffusion
Adding extra search path vae C:/AI/SDNEXT/automatic/models/VAE
Adding extra search path loras C:/AI/SDNEXT/automatic/models/Lora
Adding extra search path loras C:/AI/SDNEXT/automatic/models/LyCORIS
Adding extra search path upscale_models C:/AI/SDNEXT/automatic/models/ESRGAN
Adding extra search path upscale_models C:/AI/SDNEXT/automatic/models/RealESRGAN
Adding extra search path upscale_models C:/AI/SDNEXT/automatic/models/SwinIR
Adding extra search path embeddings C:/AI/SDNEXT/automatic/embeddings
Adding extra search path hypernetworks C:/AI/SDNEXT/automatic/models/hypernetworks
Adding extra search path controlnet C:/AI/SDNEXT/automatic/models/ControlNet
C:\AI\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py:164: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if text_input is not "":

**Comment by kijai** [comment]
That was already fixed earlier.
