### ISSUE TITLE
New Error "Task token should be the only token in the text".  After fix this Error: using , flash_attention_2 for attention , FlashAttention2 has been toggled on,

### ISSUE THREAD

**Issue by Erwin11** [kijai/ComfyUI-Florence2#2]
Hi,I installed it ,then run workflow gets this Error:

![ComfyUI](https://github.com/kijai/ComfyUI-Florence2/assets/6300501/07cd2d0f-a470-49bf-8545-d669fb591be6)

I had installed requirements.txt below on windows :
transformers   is   4.38.0
matplotlib  is  3.8.0

also I follow this Error info, try to install flash-attn （https://github.com/Dao-AILab/flash-attention）

pip install flash-attn --no-build-isolation

get this Error :
![111](https://github.com/kijai/ComfyUI-Florence2/assets/6300501/5cb96646-3353-43f0-963d-f09754ab025b)

After that， I read https://github.com/Dao-AILab/flash-attention/releases/tag/v2.5.9.post1
It seems linux only. 
Is that not support on Windows yet?  Thanks.

**Comment by Kryptonic83** [comment]
I got the same error by default, but changing the attention to sdpa works.

**Comment by Erwin11** [comment]
@Kryptonic83   thanks man, switch other attention  mode is works.
meanwhile, I found windows version for it :
https://github.com/bdashore3/flash-attention/releases

1: finding words like this: cp311-cp311-win_amd64 to check your version.
python_embeded>python -m pip debug --verbose  
2: download https://github.com/bdashore3/flash-attention/releases   flash-attentio-XXX-your-version.whl
3:pip install it 
![flash—attentionOK](https://github.com/kijai/ComfyUI-Florence2/assets/6300501/175f4f97-d600-496f-89d4-b1970dad3d68)


but I got the same error with https://github.com/kijai/ComfyUI-Florence2/issues/3  
no text is works. It will gets error when I typed key words

![ComfyUI](https://github.com/kijai/ComfyUI-Florence2/assets/6300501/5e231f06-6504-4d03-8d2f-1f8f30e665a1)

**Comment by kijai** [comment]
Not all the tasks support additional text input, I'll make that error clearer in the future.

I should really change the default attention type now that I got it working without flash_attn too...

**Comment by Erwin11** [comment]
Following example image in readme.md  , it works.
I suggest using eager as the default after comparing it with sdpa.
