### ISSUE TITLE
[Feature Request] Separate Region_caption objects 

### ISSUE THREAD

**Issue by toyxyz** [kijai/ComfyUI-Florence2#27]
Thanks for the great work as always! 

Is it possible to separate the masks of only certain captions - for example, 'person' - in Region_caption? 

Currently, the regions of all captions are combined into one mask.

![image](https://github.com/kijai/ComfyUI-Florence2/assets/8006000/1c9d4531-4c97-4c01-82d5-6b41d4860f2d)

**Comment by kijai** [comment]
It could be easily done, but I'm unsure how to deal with it when the input is a video though...

**Comment by gseth** [comment]
> It could be easily done, but I'm unsure how to deal with it when the input is a video though...

Maybe give an option like yolo world implementation. This is way better to be honest. Mask combine or select mask via a number would be awesome. Mask separation is really needed here. If you can do something would appreciate it.

**Comment by kijai** [comment]
Okay done like this for now:

![image](https://github.com/kijai/ComfyUI-Florence2/assets/40791699/3abc18a1-057e-4d08-bcb5-720dd956ccc4)

For videos it just uses the old behaviour for now.
Also need to update KJNodes for the mask selection if required.

**Comment by kijai** [comment]
Added selection for the indexes, I realize this should be separate node as it's bit clumsy to use when you don't initially know the indexes:

![image](https://github.com/kijai/ComfyUI-Florence2/assets/40791699/0553d3cc-c758-4f61-b18b-463e2cd912e5)

**Comment by toyxyz** [comment]
Thank you!
https://github.com/kijai/ComfyUI-Florence2/assets/8006000/73f3cced-098b-400a-aaf3-cb338e9794d8

**Comment by gseth** [comment]
@kijai thanks a lot 🙏
