### ISSUE TITLE
RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same

### ISSUE THREAD

**Issue by jinxishe** [kijai/ComfyUI-Florence2#30]
When I use 'florence-2' to extract a caption from an image and then use that caption as a positive prompt to regenerate an image, I encounter the following error. It seems there is a conflict between the model loader for 'florence-2' and the checkpoint.

![workflow](https://github.com/kijai/ComfyUI-Florence2/assets/25061293/2a8e6a80-1e21-45ac-91b4-c6c2a65de037)
![011884b7-d107-4806-a74c-fc0b4b35eda8](https://github.com/kijai/ComfyUI-Florence2/assets/25061293/63078752-f015-4c8e-b044-118a611bfb3a)

**Comment by kijai** [comment]
I don't really understand how this node could cause that, all it does is provide a string for the text encoder. The error is coming from the live preview somehow. I can't reproduce this at all, same setup as you works fine for me.

**Comment by jinxishe** [comment]
> I don't really understand how this node could cause that, all it does is provide a string for the text encoder. The error is coming from the live preview somehow. I can't reproduce this at all, same setup as you works fine for me.

I restart and the problem disappeared. So STRANGE. I'll close the issue.
