### ISSUE TITLE
Install instructions issue

### ISSUE THREAD

**Issue by crystalwizard** [kijai/ComfyUI-Florence2#31]
under the install instructions you have this
=======
or if you use portable (run this in ComfyUI_windows_portable -folder):

python_embeded\python.exe -m pip install -r ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\requirements.txt
======
but the directory is  ComfyUI-Florence2, not ComfyUI-DynamiCrafterWrapper - and trying to run that command predictably fails

**Comment by kijai** [comment]
Thanks, must've missed that when I initially copied the instructions, as they are otherwise same. Fixed.
