### ISSUE TITLE
Feature request: Ability to add more models via node

### ISSUE THREAD

**Issue by EnragedAntelope** [kijai/ComfyUI-Florence2#42]
Hi,
Thank you again for your work on this! 
As there are now several finetunes of Florence, could it be made possible to add them via the node in the UI?
Example:
https://huggingface.co/thwri/CogFlorence-2.1-Large

I can manually add this in the nodes.py and it works, but my change gets overwritten with every new update to the repo.

Thank you!

**Comment by kijai** [comment]
Added that one along with https://huggingface.co/NikshepShetty/Florence-2-pixelprose now.

![image](https://github.com/user-attachments/assets/7cdd6a71-2c5d-4ca3-9713-8d8e7cba3f89)

Do you know of any other finetunes worth it?

**Comment by EnragedAntelope** [comment]
Thank you so much! Only other one that I'd consider is https://huggingface.co/MiaoshouAI/Florence-2-base-PromptGen but FYI that would need one more "Task" added for <GENERATE_PROMPT> .

**Comment by kijai** [comment]
> Thank you so much! Only other one that I'd consider is https://huggingface.co/MiaoshouAI/Florence-2-base-PromptGen but FYI that would need one more "Task" added for <GENERATE_PROMPT> .

Already done that actually, also added a node to simply load any folder as model from the LLM -folder.
