### ISSUE TITLE
Add updated Florence model from Thwri

### ISSUE THREAD

**Issue by EnragedAntelope** [kijai/ComfyUI-Florence2#60]
Hi, thank you for adding the models that you did!
Thwri made his Florence finetune even better :) . Can that be added please?
https://huggingface.co/thwri/CogFlorence-2.2-Large

Thank you!

**Comment by kijai** [comment]
You can actually use any model with the Florence2ModelLoader -node, it looks for them in the ComfyUI/LLM -folder.

But I also added this to the autodownloader node now.

**Comment by EnragedAntelope** [comment]
You're awesome, thanks! I did not realize I could have manually added like that, sorry. Thank you again!
