### ISSUE TITLE
Florence2Model Missing 

### ISSUE THREAD

**Issue by ngv-sama** [kijai/ComfyUI-Florence2#61]
![image](https://github.com/user-attachments/assets/e8c6d12f-a909-4489-84cd-6661cf774783)

As shown in the image, despite installing the custom node from the manager and manually from the git-cli I am unable to load the Florence2ModelLoader. Please help!

I additionally got this error as well:

> [ERROR] An error occurred while retrieving information for the 'Florence2ModelLoader' node.
> Traceback (most recent call last):
>   File "C:\Users\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 447, in get_object_info
>     out[x] = node_info(x)
>              ^^^^^^^^^^^^
>   File "C:\Users\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 424, in node_info
>     info['input'] = obj_class.INPUT_TYPES()
>                     ^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 141, in INPUT_TYPES
>     "model": ([item.name for item in Path(folder_paths.models_dir, "LLM").iterdir() if item.is_dir()],),
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 141, in <listcomp>
>     "model": ([item.name for item in Path(folder_paths.models_dir, "LLM").iterdir() if item.is_dir()],),
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "pathlib.py", line 931, in iterdir
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\nikhi\\Downloads\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\ComfyUI\\models\\LLM'
> 
> FETCH DATA from: C:\Users\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
> [ERROR] An error occurred while retrieving information for the 'Florence2ModelLoader' node.
> Traceback (most recent call last):
>   File "C:\Users\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 447, in get_object_info
>     out[x] = node_info(x)
>              ^^^^^^^^^^^^
>   File "C:\Users\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 424, in node_info
>     info['input'] = obj_class.INPUT_TYPES()
>                     ^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 141, in INPUT_TYPES
>     "model": ([item.name for item in Path(folder_paths.models_dir, "LLM").iterdir() if item.is_dir()],),
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 141, in <listcomp>
>     "model": ([item.name for item in Path(folder_paths.models_dir, "LLM").iterdir() if item.is_dir()],),
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "pathlib.py", line 931, in iterdir
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\ComfyUI\\models\\LLM'

**Comment by kijai** [comment]
Seems it bugs out if you don't have that LLM folder in ComfyUI/models. You would need to put a model there anyway to load it, if you use the other node that has auto download, it will create that folder and put whatever it downloads there too.

**Comment by ngv-sama** [comment]
@kijai thanks for such a quick response! Figured it might be something along those lines. I'll use the other node then. Cheers!

**Comment by ruichang555** [comment]
Kijai,
 Do I need to download other Jason files (like preprocessor) besides the tensor into LLM? Thx!
