### ISSUE TITLE
Add more Model Repositories

### ISSUE THREAD

**Issue by gonzalu** [kijai/ComfyUI-Florence2#67]
Can I simply add the URL to a model into the nodes.py custom node script? 

I want to try other models like this one: 

https://huggingface.co/gokaygokay/Florence-2-Flux-Large

Or, can you add a mechanism for using any model we download or create? 

Thank you for your help and a FANTASTIC custom node :D

**Comment by kijai** [comment]
You can add any model by placing it (the whole folder) to ComfyUI/models/LLM. Some models add new prompt keys though and those have to be added in the code.

Added this to the downloader now too.

**Comment by gonzalu** [comment]
AWESOME, thank you :D
