### ISSUE TITLE
The segmentation results for some images are incorrect.

### ISSUE THREAD

**Issue by SofiaRin** [kijai/ComfyUI-Florence2#69]
Hello, I found that when executing the referring expression segmentation task, the output masks for some images of people and animals appear to be completely incorrect. Could this be due to incorrect node parameter settings? 

By the way, is there any documentation that explains the meanings of the node parameters?

![Snipaste_2024-09-09_20-49-47](https://github.com/user-attachments/assets/908106ec-268d-477a-b8ad-e587d15e9ed6)
![Snipaste_2024-09-09_20-45-31](https://github.com/user-attachments/assets/271f5497-9611-4e14-b53e-ac2621698d95)
![Snipaste_2024-09-09_20-43-24](https://github.com/user-attachments/assets/d2db5c5b-5603-4ecb-a5f4-ce5cb1ed97cd)
![Snipaste_2024-09-09_20-53-00](https://github.com/user-attachments/assets/7483ecf0-1671-4a80-85b1-fd0a6fef97f5)

**Comment by kijai** [comment]
The model in general is just not very good at segmentation, would recommend checking out Florence+SAM2 instead:

https://github.com/kijai/ComfyUI-segment-anything-2

**Comment by SofiaRin** [comment]
Thank you, I'll take a look at that.
