### ISSUE TITLE
No models installed while installing ComfyUI-Florence2

### ISSUE THREAD

**Issue by schoenid** [kijai/ComfyUI-Florence2#70]
In your readme you state: 'Supports the following models, which are automatically downloaded to ComfyUI/LLM'...

1. I've tried to install it via Manager, but there are no models nor a 'ComfyUI/LLM' folder.
2. I've tried to use the command 'git clone https://github.com/kijai/ComfyUI-Florence2' inside the 'ComfyUI\custom_nodes' folder.

Both without success. While starting the UI I've got an error:
```
[ERROR] An error occurred while retrieving information for the 'Florence2ModelLoader' node.
Traceback (most recent call last):
  File "G:\SD\Packages\ComfyUI\server.py", line 486, in get_object_info
    out[x] = node_info(x)
  File "G:\SD\Packages\ComfyUI\server.py", line 454, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "G:\SD\Packages\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 146, in INPUT_TYPES
    "model": ([item.name for item in Path(folder_paths.models_dir, "LLM").iterdir() if item.is_dir()], {"tooltip": "models are expected to be in Comfyui/LLM folder"}),
  File "G:\SD\Packages\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 146, in <listcomp>
    "model": ([item.name for item in Path(folder_paths.models_dir, "LLM").iterdir() if item.is_dir()], {"tooltip": "models are expected to be in Comfyui/LLM folder"}),
  File "pathlib.py", line 1017, in iterdir
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'G:\\SD\\Packages\\ComfyUI\\models\\LLM'
```

One thing I found remarkable:
The readme states, that models go to `ComfyUI/LLM`, but the error says, those should be located in `ComfyUI\models\LLM` (see the last line in the error message).
Which one is correct? (I guess the second one ...)

Some system info:
```
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: G:\SD\Packages\ComfyUI\venv\Scripts\python.exe
** ComfyUI Path: G:\SD\Packages\ComfyUI

### ComfyUI Revision: 2652 [0c7c98a9] | Released on '2024-09-05'
```

**Comment by kijai** [comment]
There's a node for downloading models separate from the model loader node. That line you noticed in the readme is indeed a typo, thanks, I'll fix that, second one is of course correct.

**Comment by ZhianLin** [comment]
It may be a node conflict. You can use the method demonstrated in the GIF below to find a replacement node。
(可能是节点冲突了，可以用下面GIF演示的的方法查找替换的节点)
![ComfyUI节点冲突时替换的节点-2024-09-10](https://github.com/user-attachments/assets/6335f233-ce3d-4b96-9fdd-f128051eb127)

**Comment by schoenid** [comment]
Works great.
Thank you both!

**Comment by nemilya** [comment]
@ZhianLin thanks! this tip also solved by problem

**Comment by ZhianLin** [comment]
> @ZhianLin thanks! this tip also solved by problem

🤝

**Comment by lavibeats** [comment]
When I replaced, It worked. Thanks !
