### ISSUE TITLE
Its not working ? it just says its done ! empty 

### ISSUE THREAD

**Issue by MIKETUFFIN66** [kijai/ComfyUI-Florence2#87]
Hello, 
What you see is an example of a working model, but in my case .. its empty ! there is no caption .. i downloaded the model and every thing but no luck .. can any one please help me with this?
thanks in advance

![empty](https://github.com/user-attachments/assets/614c81ac-8a22-47c5-97e0-daa2ac1c4050)

**Comment by kijai** [comment]
I don't know this workflow, is that everything in a group node? I can't really offer support for custom workflows, if one of my examples don't work and you get some errors in the log, then I can take a look.

**Comment by MIKETUFFIN66** [comment]
> I don't know this workflow, is that everything in a group node? I can't really offer support for custom workflows, if one of my examples don't work and you get some errors in the log, then I can take a look.

yes its a group note , thank you . i managed to solve the problem .. thanks
