### ISSUE TITLE
Feature request: PromptGen V2.0

### ISSUE THREAD

**Issue by ManOrMonster** [kijai/ComfyUI-Florence2#95]
I'm sure you know this, but I don't see any mention of it here. 

[PromptGen V2.0](https://huggingface.co/MiaoshouAI/Florence-2-base-PromptGen-v2.0) is out. It has a new `<ANALYZE>` instruction, and a new instruction for `<MIXED_CAPTION_PLUS>`.

MiaoshouAI has their own [custom node](https://github.com/miaoshouai/ComfyUI-Miaoshouai-Tagger) for this, but I'd prefer to just stick with yours.

**Comment by kijai** [comment]
Already added 4 days ago:

https://github.com/kijai/ComfyUI-Florence2/commit/599ca4a40f9fa8a970b5c05e9fc44e698ce345e3

**Comment by ManOrMonster** [comment]
Well, guess I need to update!
